# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_titlw',
            new_name='song_title',
        ),
    ]
